export const isoLang = {
    ab: { name: 'Abkhaz', original: 'аҧсуа' },
    aa: { name: 'Afar', original: 'Afaraf' },
    af: { name: 'Afrikaans', original: 'Afrikaans' },
    ak: { name: 'Akan', original: 'Akan' },
    sq: { name: 'Albanian', original: 'Shqip' },
    am: { name: 'Amharic', original: 'አማርኛ' },
    ar: { name: 'Arabic', original: 'العربية' },
    an: { name: 'Aragonese', original: 'Aragonés' },
    hy: { name: 'Armenian', original: 'Հայերեն' },
    as: { name: 'Assamese', original: 'অসমীয়া' },
    av: { name: 'Avaric', original: 'авар мацӀ, магӀарул мацӀ' },
    ae: { name: 'Avestan', original: 'avesta' },
    ay: { name: 'Aymara', original: 'aymar aru' },
    az: { name: 'Azerbaijani', original: 'azərbaycan dili' },
    bm: { name: 'Bambara', original: 'bamanankan' },
    ba: { name: 'Bashkir', original: 'башҡорт теле' },
    eu: { name: 'Basque', original: 'euskara, euskera' },
    be: { name: 'Belarusian', original: 'Беларуская' },
    bn: { name: 'Bengali', original: 'বাংলা' },
    bh: { name: 'Bihari', original: 'भोजपुरी' },
    bi: { name: 'Bislama', original: 'Bislama' },
    bs: { name: 'Bosnian', original: 'bosanski jezik' },
    br: { name: 'Breton', original: 'brezhoneg' },
    bg: { name: 'Bulgarian', original: 'български език' },
    my: { name: 'Burmese', original: 'ဗမာစာ' },
    ca: { name: 'Catalan; Valencian', original: 'Català' },
    ch: { name: 'Chamorro', original: 'Chamoru' },
    ce: { name: 'Chechen', original: 'нохчийн мотт' },
    ny: { name: 'Chichewa; Chewa; Nyanja', original: 'chiCheŵa, chinyanja' },
    zh: { name: 'Chinese', original: '中文 (Zhōngwén), 汉语, 漢語' },
    cv: { name: 'Chuvash', original: 'чӑваш чӗлхи' },
    kw: { name: 'Cornish', original: 'Kernewek' },
    co: { name: 'Corsican', original: 'corsu, lingua corsa' },
    cr: { name: 'Cree', original: 'ᓀᐦᐃᔭᐍᐏᐣ' },
    hr: { name: 'Croatian', original: 'hrvatski' },
    cs: { name: 'Czech', original: 'česky, čeština' },
    da: { name: 'Danish', original: 'dansk' },
    dv: { name: 'Divehi; Dhivehi; Maldivian;', original: 'ދިވެހި' },
    nl: { name: 'Dutch', original: 'Nederlands, Vlaams' },
    en: { name: 'English', original: 'English' },
    eo: { name: 'Esperanto', original: 'Esperanto' },
    et: { name: 'Estonian', original: 'eesti, eesti keel' },
    ee: { name: 'Ewe', original: 'Eʋegbe' },
    fo: { name: 'Faroese', original: 'føroyskt' },
    fj: { name: 'Fijian', original: 'vosa Vakaviti' },
    fi: { name: 'Finnish', original: 'suomi, suomen kieli' },
    fr: { name: 'French', original: 'français' },
    ff: { name: 'Fula; Fulah; Pulaar; Pular', original: 'Fulfulde, Pulaar, Pular' },
    gl: { name: 'Galician', original: 'Galego' },
    ka: { name: 'Georgian', original: 'ქართული' },
    de: { name: 'German', original: 'Deutsch' },
    el: { name: 'Greek, Modern', original: 'Ελληνικά' },
    gn: { name: 'Guaraní', original: 'Avañeẽ' },
    gu: { name: 'Gujarati', original: 'ગુજરાતી' },
    ht: { name: 'Haitian; Haitian Creole', original: 'Kreyòl ayisyen' },
    ha: { name: 'Hausa', original: 'Hausa, هَوُسَ' },
    he: { name: 'Hebrew (modern)', original: 'עברית' },
    hz: { name: 'Herero', original: 'Otjiherero' },
    hi: { name: 'Hindi', original: 'हिन्दी, हिंदी' },
    ho: { name: 'Hiri Motu', original: 'Hiri Motu' },
    hu: { name: 'Hungarian', original: 'Magyar' },
    ia: { name: 'Interlingua', original: 'Interlingua' },
    id: { name: 'Indonesian', original: 'Bahasa Indonesia' },
    ie: {
        name: 'Interlingue',
        original: 'Originally called Occidental; then Interlingue after WWII',
    },
    ga: { name: 'Irish', original: 'Gaeilge' },
    ig: { name: 'Igbo', original: 'Asụsụ Igbo' },
    ik: { name: 'Inupiaq', original: 'Iñupiaq, Iñupiatun' },
    io: { name: 'Ido', original: 'Ido' },
    is: { name: 'Icelandic', original: 'Íslenska' },
    it: { name: 'Italian', original: 'Italiano' },
    iu: { name: 'Inuktitut', original: 'ᐃᓄᒃᑎᑐᑦ' },
    ja: { name: 'Japanese', original: '日本語 (にほんご／にっぽんご)' },
    jv: { name: 'Javanese', original: 'basa Jawa' },
    kl: { name: 'Kalaallisut, Greenlandic', original: 'kalaallisut, kalaallit oqaasii' },
    kn: { name: 'Kannada', original: 'ಕನ್ನಡ' },
    kr: { name: 'Kanuri', original: 'Kanuri' },
    ks: { name: 'Kashmiri', original: 'कश्मीरी, كشميري‎' },
    kk: { name: 'Kazakh', original: 'Қазақ тілі' },
    km: { name: 'Khmer', original: 'ភាសាខ្មែរ' },
    ki: { name: 'Kikuyu, Gikuyu', original: 'Gĩkũyũ' },
    rw: { name: 'Kinyarwanda', original: 'Ikinyarwanda' },
    ky: { name: 'Kirghiz, Kyrgyz', original: 'кыргыз тили' },
    kv: { name: 'Komi', original: 'коми кыв' },
    kg: { name: 'Kongo', original: 'KiKongo' },
    ko: { name: 'Korean', original: '한국어 (韓國語), 조선말 (朝鮮語)' },
    ku: { name: 'Kurdish', original: 'Kurdî, كوردی‎' },
    kj: { name: 'Kwanyama, Kuanyama', original: 'Kuanyama' },
    la: { name: 'Latin', original: 'latine, lingua latina' },
    lb: { name: 'Luxembourgish, Letzeburgesch', original: 'Lëtzebuergesch' },
    lg: { name: 'Luganda', original: 'Luganda' },
    li: { name: 'Limburgish, Limburgan, Limburger', original: 'Limburgs' },
    ln: { name: 'Lingala', original: 'Lingála' },
    lo: { name: 'Lao', original: 'ພາສາລາວ' },
    lt: { name: 'Lithuanian', original: 'lietuvių kalba' },
    lu: { name: 'Luba-Katanga', original: '' },
    lv: { name: 'Latvian', original: 'latviešu valoda' },
    gv: { name: 'Manx', original: 'Gaelg, Gailck' },
    mk: { name: 'Macedonian', original: 'македонски јазик' },
    mg: { name: 'Malagasy', original: 'Malagasy fiteny' },
    ms: { name: 'Malay', original: 'bahasa Melayu, بهاس ملايو‎' },
    ml: { name: 'Malayalam', original: 'മലയാളം' },
    mt: { name: 'Maltese', original: 'Malti' },
    mi: { name: 'Māori', original: 'te reo Māori' },
    mr: { name: 'Marathi (Marāṭhī)', original: 'मराठी' },
    mh: { name: 'Marshallese', original: 'Kajin M̧ajeļ' },
    mn: { name: 'Mongolian', original: 'монгол' },
    na: { name: 'Nauru', original: 'Ekakairũ Naoero' },
    nv: { name: 'Navajo, Navaho', original: 'Diné bizaad, Dinékʼehǰí' },
    nb: { name: 'Norwegian Bokmål', original: 'Norsk bokmål' },
    nd: { name: 'North Ndebele', original: 'isiNdebele' },
    ne: { name: 'Nepali', original: 'नेपाली' },
    ng: { name: 'Ndonga', original: 'Owambo' },
    nn: { name: 'Norwegian Nynorsk', original: 'Norsk nynorsk' },
    no: { name: 'Norwegian', original: 'Norsk' },
    ii: { name: 'Nuosu', original: 'ꆈꌠ꒿ Nuosuhxop' },
    nr: { name: 'South Ndebele', original: 'isiNdebele' },
    oc: { name: 'Occitan', original: 'Occitan' },
    oj: { name: 'Ojibwe, Ojibwa', original: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
    cu: { name: 'Old Church Slavonic', original: 'ѩзыкъ словѣньскъ' },
    om: { name: 'Oromo', original: 'Afaan Oromoo' },
    or: { name: 'Oriya', original: 'ଓଡ଼ିଆ' },
    os: { name: 'Ossetian, Ossetic', original: 'ирон æвзаг' },
    pa: { name: 'Panjabi, Punjabi', original: 'ਪੰਜਾਬੀ, پنجابی‎' },
    pi: { name: 'Pāli', original: 'पाऴि' },
    fa: { name: 'Persian', original: 'فارسی' },
    pl: { name: 'Polish', original: 'polski' },
    ps: { name: 'Pashto, Pushto', original: 'پښتو' },
    pt: { name: 'Portuguese', original: 'Português' },
    qu: { name: 'Quechua', original: 'Runa Simi, Kichwa' },
    rm: { name: 'Romansh', original: 'rumantsch grischun' },
    rn: { name: 'Kirundi', original: 'kiRundi' },
    ro: { name: 'Romanian, Moldavian, Moldovan', original: 'română' },
    ru: { name: 'Russian', original: 'русский язык' },
    sa: { name: 'Sanskrit (Saṁskṛta)', original: 'संस्कृतम्' },
    sc: { name: 'Sardinian', original: 'sardu' },
    sd: { name: 'Sindhi', original: 'सिन्धी, سنڌي، سندھی‎' },
    se: { name: 'Northern Sami', original: 'Davvisámegiella' },
    sm: { name: 'Samoan', original: 'gagana faa Samoa' },
    sg: { name: 'Sango', original: 'yângâ tî sängö' },
    sr: { name: 'Serbian', original: 'српски језик' },
    gd: { name: 'Scottish Gaelic; Gaelic', original: 'Gàidhlig' },
    sn: { name: 'Shona', original: 'chiShona' },
    si: { name: 'Sinhala, Sinhalese', original: 'සිංහල' },
    sk: { name: 'Slovak', original: 'slovenčina' },
    sl: { name: 'Slovene', original: 'slovenščina' },
    so: { name: 'Somali', original: 'Soomaaliga, af Soomaali' },
    st: { name: 'Southern Sotho', original: 'Sesotho' },
    es: { name: 'Spanish; Castilian', original: 'español, castellano' },
    su: { name: 'Sundanese', original: 'Basa Sunda' },
    sw: { name: 'Swahili', original: 'Kiswahili' },
    ss: { name: 'Swati', original: 'SiSwati' },
    sv: { name: 'Swedish', original: 'svenska' },
    ta: { name: 'Tamil', original: 'தமிழ்' },
    te: { name: 'Telugu', original: 'తెలుగు' },
    tg: { name: 'Tajik', original: 'тоҷикӣ, toğikī, تاجیکی‎' },
    th: { name: 'Thai', original: 'ไทย' },
    ti: { name: 'Tigrinya', original: 'ትግርኛ' },
    bo: { name: 'Tibetan Standard, Tibetan, Central', original: 'བོད་ཡིག' },
    tk: { name: 'Turkmen', original: 'Türkmen, Түркмен' },
    tl: { name: 'Tagalog', original: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
    tn: { name: 'Tswana', original: 'Setswana' },
    to: { name: 'Tonga (Tonga Islands)', original: 'faka Tonga' },
    tr: { name: 'Turkish', original: 'Türkçe' },
    ts: { name: 'Tsonga', original: 'Xitsonga' },
    tt: { name: 'Tatar', original: 'татарча, tatarça, تاتارچا‎' },
    tw: { name: 'Twi', original: 'Twi' },
    ty: { name: 'Tahitian', original: 'Reo Tahiti' },
    ug: { name: 'Uighur, Uyghur', original: 'Uyƣurqə, ئۇيغۇرچە‎' },
    uk: { name: 'Ukrainian', original: 'українська' },
    ur: { name: 'Urdu', original: 'اردو' },
    uz: { name: 'Uzbek', original: 'zbek, Ўзбек, أۇزبېك‎' },
    ve: { name: 'Venda', original: 'Tshivenḓa' },
    vi: { name: 'Vietnamese', original: 'Tiếng Việt' },
    vo: { name: 'Volapük', original: 'Volapük' },
    wa: { name: 'Walloon', original: 'Walon' },
    cy: { name: 'Welsh', original: 'Cymraeg' },
    wo: { name: 'Wolof', original: 'Wollof' },
    fy: { name: 'Western Frisian', original: 'Frysk' },
    xh: { name: 'Xhosa', original: 'isiXhosa' },
    yi: { name: 'Yiddish', original: 'ייִדיש' },
    yo: { name: 'Yoruba', original: 'Yorùbá' },
    za: { name: 'Zhuang, Chuang', original: 'Saɯ cueŋƅ, Saw cuengh' },
}
